config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions" }

  get '/map-projects/call',    to: 'application#map_projects_call',    as: :map_projects_call
  get '/menu-responsive/call', to: 'application#menu_responsive_call', as: :menu_responsive_call
  get '/admin-nav/call',       to: 'application#admin_nav_call',       as: :admin_nav_call
  
  root                          to: 'pages#home'
  get '/definition',            to: 'pages#definition'
  get '/perspectives/timeline', to: 'pages#timeline'
  get '/perspectives/article',  to: 'pages#article'
  get '/resources',             to: 'pages#resources'
  get '/join',                  to: 'pages#join'
  get '/about',                 to: 'pages#about'
  get '/projects/:id',          to: 'pages#project',             as: :project
  get '/map-projects/search',   to: 'pages#map_projects_search', as: :map_projects_search
  get "/robots.:format",        to: "pages#robots"
  get "/legal-notices",         to: "pages#legal_notices"
  get "/privacy-notice",        to: "pages#privacy_notice"

  post '/join/requesters/create',        to: 'requesters#create', as: :new_requester

  # constraints subdomain: /admin/ do
    get   ':slug/welcome',   to: 'admin#welcome',   as: :admin_welcome
    get   ':slug/dashboard', to: 'admin#dashboard', as: :admin_dashboard

    get   ':slug/dashboard/analytics',       to: 'admin#analytics',       as: :admin_analytics
    get   ':slug/dashboard/analytics/excel', to: 'admin#analytics_excel', as: :admin_analytics_excel
    
    get   ':slug/dashboard/requesters/index',     to: 'admin#requesters',        as: :admin_requesters
    get   ':slug/dashboard/requesters/excel',     to: 'admin#requesters_excel',  as: :admin_requesters_excel
    get   ':slug/dashboard/requesters/:id/excel', to: 'admin#requester_excel',   as: :admin_requester_excel
    patch ':slug/dashboard/update/requesters',    to: 'admin#update_requesters', as: :admin_update_requesters
    
    get   ':slug/dashboard/projects/new',   to: 'admin#project_new',  as: :admin_new_project
    get   ':slug/dashboard/projects/index', to: 'admin#projects',     as: :admin_projects
    get   ':slug/dashboard/projects/:id',   to: 'admin#project_show', as: :admin_project_show

    post  ':slug/dashboard/projects/create',      to: 'projects#create',  as: :admin_create_project
    patch ':slug/dashboard/projects/:id/update',  to: 'projects#update',  as: :admin_update_project
    delete ':slug/dashboard/projects/:id/delete', to: 'projects#destroy', as: :admin_destroy_project

    get ':slug/dashboard/sandbox', to: 'admin#sandbox', as: :admin_sandbox
  # end

  constraints(host: /^(?!www\.)/i) do
    get '(*any)' => redirect { |params, request|
      URI.parse(request.url).tap { |uri| uri.host = "www.#{uri.host}" }.to_s
    }
  end
end

app/views/admin/analytics.html.erb
<section class="h-max">

	<h1 class="flex-cent m-auto mb-50">Admin Dashboard | Analytics</h1>

	<div class="flex-row-wrap-cent">
		
		<div class="p-50-rp-25">
			<div class="background-white soft-ml-box-shadow flex-col p-25" style="width:250px;height:250px;">
				<p class="m-0"><span class="mr-05"><%= svg('ubisoft_user_black_25') %></span> Visitors</p>
				<span class="text-cent text-blue h-max flex-cent" style="font-size:4rem"><%= @agents_count %></span>
			</div>
		</div>

		<div class="p-50-rp-25">
			<div class="background-white soft-ml-box-shadow flex-col p-25" style="width:250px;height:250px;">
				<p class="m-0"><span class="mr-05"><%= svg('ubisoft_localization_25') %></span> Top location</p>
				<span class="text-cent text-blue h-max flex-cent" style="font-size:2rem"><%= @top_location %></span>
			</div>
		</div>

		<div class="p-50-rp-25">
			<div class="background-white soft-ml-box-shadow flex-col p-25" style="width:250px;height:250px;">
				<p class="m-0"><span class="mr-05"><%= svg('ubisoft_localization_25') %></span> Top city</p>
				<span class="text-cent text-blue h-max flex-cent" style="font-size:2rem"><%= @top_city %></span>
			</div>
		</div>

		<div class="p-50-rp-25">
			<div class="background-white soft-ml-box-shadow flex-col p-25" style="width:250px;height:250px;">
				<p class="m-0"><span class="mr-05"><%= svg('ubisoft_print_25') %></span> Top printable project</p>
				<span class="text-cent text-blue h-max flex-cent" style="font-size:2rem"><%= @top_printable %></span>
			</div>
		</div>

	</div>

	<!-- <h1>Printables</h1> -->

	<%#= render "admin/partials/tables/printables" %>

	<!-- <div class="mt-50"></div> -->

	<!-- <h1>Locations</h1> -->

	<%#= render "admin/partials/tables/agents_countries" %>

	<!-- <h1>Cities</h1> -->

	<%#= render "admin/partials/tables/agents_cities" %>
	
	<div class="flex-end">
		<%= link_to 'Download as Excel', admin_analytics_excel_path(format: :xlsx, slug:@slug), class: "radius-05 excel-btn p-small" %>
	</div>

</section>

app/views/admin/dashboard.html.erb
<section class="h-vh">

	<h1 class="flex-cent m-auto mb-50">Admin Dashboard</h1>

	<div class="flex-row-wrap-cent">
		
		<% if @authorize_admins.include?(current_user.email) %>
			<div class="p-50-rp-25">
				<div class="background-white soft-ml-box-shadow flex-col-ard-cent p-25" style="width:250px;height:250px;">
					<%= svg('ubisoft_group') %>
					<%= link_to "requesters", admin_requesters_path(slug:@slug), class:"main-btn" %>
				</div>
			</div>

			<div class="p-50-rp-25">
				<div class="background-white soft-ml-box-shadow flex-col-ard-cent p-25" style="width:250px;height:250px;">
					<%= svg('ubisoft_rocket') %>
					<%= link_to "projects", admin_projects_path(slug:@slug), class:"main-btn" %>
				</div>
			</div>
		<% end %>

		<div class="p-50-rp-25">
			<div class="background-white soft-ml-box-shadow flex-col-ard-cent p-25" style="width:250px;height:250px;">
				<%= svg('ubisoft_metrics') %>
				<%= link_to "analytics", admin_analytics_path(slug:@slug), class:"main-btn" %>
			</div>
		</div>

	</div>

</section>

app/views/admin/project_new.html.erb
<section class="h-max">

	<h1 class="text-cent">New project</h1>

	<%= form_for @project, url: admin_create_project_path(slug:@slug), method: :post, html: { class:"mt-50 background-magic-grey p-25 radius-05", id:"new_project" } do |f| %>

		<%= render "admin/partials/forms/project_inputs", f:f %>
		<%= render "admin/partials/forms/bodies/create_english", f:f %>
		<%= render "admin/partials/forms/bodies/create_french", f:f %>

	    <div class="flex-end mt-30 relative">
	    	<%= f.submit "Create", class:"main-btn p-auto" %>
	    </div>

	<% end -%>

</section> 

app/views/admin/project_show.html.erb
<section class="h-max">

	<div class="flex-col-cent m-auto">
		<h1><%=sanitize @project.title %></h1>
		<p class="text-cent m-0"><%=sanitize @project.company %></p>
		<p class="text-cent p-small m-0 text-strong-grey"><%=sanitize @project.actor %></p>
	</div>

	<div class="flex-col-start mt-50">
		<p class="rp-small m-0">Contact : <span class="text-strong-grey"><%=sanitize @project.contact %></span></p>
		<p class="rp-small m-0">Stakes : <span class="text-strong-grey"><%=sanitize @project.stakes.join(', ') %></span></p>
		<p class="rp-small m-0">Countries : <span class="text-strong-grey"><%=sanitize @project.countries.join(', ') %></span></p>
		<p class="rp-small m-0">Media : <span class="text-strong-grey"><%=sanitize @project.media %></span></p>
		<p class="rp-small m-0">Website : <span class="text-strong-grey"><%=sanitize @project.website %></span></p>
		<%= link_to "See project", project_path(@project), class:"pad-blue mt-10" %>
	</div>

	<%= form_for @project, url: admin_update_project_path(id:@project,slug:@slug), method: :patch, html: { class:"mt-50 background-magic-grey p-25 radius-05", id:"edit_project" } do |f| %>

		<%= render "admin/partials/forms/project_inputs", f:f %>

		<% if @project.bodies.empty? %>
			<%= render "admin/partials/forms/bodies/create_english", f:f %>
			<%= render "admin/partials/forms/bodies/create_french", f:f %>
		<% else %>
			<%= f.fields_for :bodies do |ff| %>
				<% if ff.object.version == "EN" %>
					<%= render "admin/partials/forms/bodies/update_english", f:f, ff:ff %>
				<% else %>
					<%= render "admin/partials/forms/bodies/update_french", f:f, ff:ff %>
				<% end -%>
			<% end -%>
		<% end -%>

	    <div class="flex-end mt-30 relative">
	    	<%= f.submit "Update", class:"main-btn p-auto" %>
	    </div>

	<% end -%>

</section> 

app/views/admin/projects.html.erb
<section class="h-max">

	<h1 class="flex-cent m-auto mb-50">Admin Dashboard</h1>

	<h1><%= "Project".pluralize(@projects_count) %> (<%= @projects_count %>)</h1>

	<div class="flex-end mb-20">
		<%= link_to "new project", admin_new_project_path(slug:@slug), class:"main-btn" %>
	</div>

	<div class="scrollable-x" >
	  <table class="text-cent">
	    <thead class="background-strong-grey">
	     	<tr class="text-white">
	     		<th>Date</th>
	     		<th>Title</th>
	     		<th>Actor</th>
	     		<th>Company</th>
	     		<th>Media</th>
	     		<th>Actions</th>
	      </tr>
	    </thead>

	    <tbody>
	      <% @projects.each do |project| %>
		      <tr class="p-small border-top light-grey">
		        <td><%= project.created_at.strftime("%d") %> - <%= project.created_at.strftime("%b") %> - <%= project.created_at.strftime("%Y") %></td>
		        <td class="max-w-300"><%=sanitize project.title %></td>
		        <td class="max-w-300"><%=sanitize project.actor %></td>
		        <td><%=sanitize project.company %></td>
		        <td><%=sanitize project.media %></td>
		        <td>
		        	<%= link_to admin_project_show_path(id:project,slug:@slug) do %>
		        		<%= svg('ubisoft_viewers_40') %>
		        	<% end -%>
		        	<%= link_to admin_destroy_project_path(id:project,slug:@slug), method: :delete, data: { confirm: 'Are you sure ?' } do %>
		        		<%= svg('ubisoft_garbage_red_20') %>
		        	<% end -%>
						</td>
		      </tr>
	      <% end %>
	    </tbody>
	  </table>

    <% if !@projects.empty? %>
      <nav class="custom-pagination">
        <%== pagy_nav(@pagy_projects) %>

        <div class="relative">
          <i class="fas fa-sort-down text-strong-grey index-1"></i>

		      <select name="pagy_items" id="items_projects" class="ml-10 radius-03 relative">
		        <option value="<%= admin_projects_path(items_projects:10) %>" <%= params[:items_projects] == '10' ? 'selected' : ''%>>10</option>
		        <option value="<%= admin_projects_path(items_projects:20) %>" <%= params[:items_projects] == '20' ? 'selected' : ''%>>20</option>
		        <option value="<%= admin_projects_path(items_projects:30) %>" <%= params[:items_projects] == '30' ? 'selected' : ''%>>30</option>
		        <option value="<%= admin_projects_path(items_projects:40) %>" <%= params[:items_projects] == '40' ? 'selected' : ''%>>40</option>
		        <option value="<%= admin_projects_path(items_projects:50) %>" <%= params[:items_projects] == '50' ? 'selected' : ''%>>50</option>
		      </select>
        </div>

        <span class="ml-05 text-strong-grey">items per page</span>
      </nav>
    <% end %>

    <% if @projects.empty? %>

      <div class="flex-cent m-auto mt-50">
        <p class="mt-10">nothing to display. . .</p>
      </div>

    <% end %>
	</div>

</section>

app/views/admin/requesters.html.erb
<section class="h-max no-padding-y">

	<h1 class="flex-cent m-auto mb-50">Admin Dashboard</h1>

	<h1><%= "Requester".pluralize(@requesters_count) %> (<%= @requesters_count %>)</h1>

	<%= form_tag admin_update_requesters_path(slug:@slug), method: :patch, class:"scrollable-x" do %>
	  <table class="text-cent">
	    <thead class="background-strong-grey">
	     	<tr class="text-white">
	     		<th>Date</th>
	        <th>Name</th>
	        <th>Email</th>
	        <th>Country</th>
	        <th>Job title</th>
	        <th>Reason</th>
	        <th>Message</th>
	        <th>Consent</th>
	        <th>Data retention period</th>
	        <th>Contacted</th>
	        <th>Unsubscribe</th>
	      </tr>
	    </thead>

	    <tbody>
	      <% @requesters.each do |requester| %>
		      <tr class="p-small border-top light-grey">
		        <td>
		        	<%= requester.created_at.strftime("%d") %> - <%= requester.created_at.strftime("%b") %> - <%= requester.created_at.strftime("%Y") %>
						</td>
						<td><%=sanitize requester.first_name %> <%=sanitize requester.last_name %></td>
						<td><%=sanitize requester.email %></td>
						<td><%=sanitize requester.country %></td>
						<td><%=sanitize requester.job_title %></td>
						<td class="max-w-300">
							<%= requester.reason.map{|r| (requester.reason.index(r) + 1).to_s + ') ' + r.to_s}.join(' ') %>
					  </td>
		        <td class="max-w-400"><%=sanitize requester.message.truncate(140) %></td>
		        <td><%= requester.consent %></td>
      			<td class="flex-col">
      				<span><%= requester.data_retention_period %></span>

      				<span><%= link_to 'Extract', admin_requester_excel_path(format: :xlsx, slug:@slug, id:requester), class: "radius-05 excel-btn mr-05" %></span>
      			</td>
		        <td>
		          <%= check_box_tag "contacted_ids[]", requester.contacted ? '' : requester.id, false, id:"contact_#{requester.id}", class:"square-ux-checkbox", disabled:requester.contacted ? true : false, checked:requester.contacted ? true : false %>
      				<%= label_tag nil, nil, for:"contact_#{requester.id}", class:"orange #{requester.contacted ? 'disabled' : ''}" %>
      			</td>
 		        <td>
		          <%= check_box_tag "unsubscribe_ids[]", requester.unsubscribe ? '' : requester.id, false, id:"unsubscribe_#{requester.id}", class:"square-ux-checkbox", disabled:requester.unsubscribe ? true : false, checked:requester.unsubscribe ? true : false %>
      				<%= label_tag nil, nil, for:"unsubscribe_#{requester.id}", class:"orange #{requester.unsubscribe ? 'disabled' : ''}" %>
      			</td>
		      </tr>
	      <% end %>
	    </tbody>
	  </table>

    <% if !@requesters.empty? %>
      <nav class="custom-pagination">
        <%== pagy_nav(@pagy_requesters) %>

        <div class="relative">
          <i class="fas fa-sort-down text-strong-grey index-1"></i>

		      <select name="pagy_items" id="items_requesters" class="ml-10 radius-03 relative">
		        <option value="<%= admin_requesters_path(items_requesters:10) %>" <%= params[:items_requesters] == '10' ? 'selected' : ''%>>10</option>
		        <option value="<%= admin_requesters_path(items_requesters:20) %>" <%= params[:items_requesters] == '20' ? 'selected' : ''%>>20</option>
		        <option value="<%= admin_requesters_path(items_requesters:30) %>" <%= params[:items_requesters] == '30' ? 'selected' : ''%>>30</option>
		        <option value="<%= admin_requesters_path(items_requesters:40) %>" <%= params[:items_requesters] == '40' ? 'selected' : ''%>>40</option>
		        <option value="<%= admin_requesters_path(items_requesters:50) %>" <%= params[:items_requesters] == '50' ? 'selected' : ''%>>50</option>
		      </select>
        </div>

        <span class="ml-05 text-strong-grey">items per page</span>
      </nav>

      <div class="flex-end mt-05 p-small">
      	<%= link_to 'Download as Excel', admin_requesters_excel_path(format: :xlsx, slug:@slug), class: "radius-05 excel-btn mr-05" %>
      	<%= button_tag "update selection", class:"main-btn radius-05 pt-14" %>
      </div>
    <% end %>

    <% if @requesters.empty? %>

      <div class="flex-cent m-auto mt-50">
        <p class="mt-10">nothing to display. . .</p>
      </div>

    <% end %>
	<% end %>

</section>

app/views/admin/sandbox.html.erb
<section class="h-max">

	<h1>remote: <%= request.remote_ip %></h1>
	<h1>ip: <%= request.ip %></h1>
	<h1>public: <%= open('http://whatismyip.akamai.com').read %></h1>

</section>

app/views/admin/welcome.html.erb
<section class="h-max">
  <div class="soft-ml-box-shadow flex-col-cent radius-05 w-max pb-25 text-cent">

    <div class="w-max background-magic-grey p-10">
      <%= image_tag 'partners/Ruby_on_Rails-logo.png', width: "40px" %>
      <h1 class="m-0">Welcome on Rails</h1>
    </div>

    <div class="flex-col-cent mt-50 p-10">

      <div class="max-w-600 mb-50">
        <%= svg('ubisoft_gear_30') %>
        <h3 class="mt-05">Configuration files</h3>

        <p class="p-rp-small">
          This Rails app was generated with <%= link_to "ubi-legal-innovation-team/templates", "https://github.com/ubi-legal-innovation-team/templates/blob/master/default.rb", target: "_blank", class: "text-underline" %>, created by the <%= link_to "Legal Innovation team", "https://www.legallab.ubisoft.org/crew", target:"_blank", class: "text-underline" %> and server-side administrated by <%= link_to "Arthur D'huy", "https://profile.ubisoft.org/#/u/adhuy?autocompletion=true", target:"_blank", class: "text-underline" %>.
        </p>
      </div>

      <div class="max-w-600 mb-50">
        <%= svg('ubisoft_rocket_30') %>
        <h3 class="mt-05">Versions management (v.1.0.0)</h3>

        <ul class="no-padding unstyle-list p-rp-small text-left">
          <li class="mb-05"><u>v1.0.0</u> : first launch and deployment on Heroku <span class="text-grey">(12, 2021)</span></li>
        </ul>
      </div>

      <div class="max-w-600 mb-100">
        <%= svg('ubisoft_home_30') %>
        <h3 class="mt-05">Current application</h3>
        <p class="p-rp-small">The current version of <span class="text-red">ruby</span> is <%= RUBY_VERSION %>.</p>
        <p class="p-rp-small">The current version of <span class="text-red">Rails</span> is <%= Rails.version %></p>
      </div>

      <%= link_to "E N T E R", admin_dashboard_path(slug:@slug), class: "pad-orange" %>

    </div>

  </div>
</section>