config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions" }

  get '/map-projects/call',    to: 'application#map_projects_call',    as: :map_projects_call
  get '/menu-responsive/call', to: 'application#menu_responsive_call', as: :menu_responsive_call
  get '/admin-nav/call',       to: 'application#admin_nav_call',       as: :admin_nav_call
  
  root                          to: 'pages#home'
  get '/definition',            to: 'pages#definition'
  get '/perspectives/timeline', to: 'pages#timeline'
  get '/perspectives/article',  to: 'pages#article'
  get '/resources',             to: 'pages#resources'
  get '/join',                  to: 'pages#join'
  get '/about',                 to: 'pages#about'
  get '/projects/:id',          to: 'pages#project',             as: :project
  get '/map-projects/search',   to: 'pages#map_projects_search', as: :map_projects_search
  get "/robots.:format",        to: "pages#robots"
  get "/legal-notices",         to: "pages#legal_notices"
  get "/privacy-notice",        to: "pages#privacy_notice"

  post '/join/requesters/create',        to: 'requesters#create', as: :new_requester

  # constraints subdomain: /admin/ do
    get   ':slug/welcome',   to: 'admin#welcome',   as: :admin_welcome
    get   ':slug/dashboard', to: 'admin#dashboard', as: :admin_dashboard

    get   ':slug/dashboard/analytics',       to: 'admin#analytics',       as: :admin_analytics
    get   ':slug/dashboard/analytics/excel', to: 'admin#analytics_excel', as: :admin_analytics_excel
    
    get   ':slug/dashboard/requesters/index',     to: 'admin#requesters',        as: :admin_requesters
    get   ':slug/dashboard/requesters/excel',     to: 'admin#requesters_excel',  as: :admin_requesters_excel
    get   ':slug/dashboard/requesters/:id/excel', to: 'admin#requester_excel',   as: :admin_requester_excel
    patch ':slug/dashboard/update/requesters',    to: 'admin#update_requesters', as: :admin_update_requesters
    
    get   ':slug/dashboard/projects/new',   to: 'admin#project_new',  as: :admin_new_project
    get   ':slug/dashboard/projects/index', to: 'admin#projects',     as: :admin_projects
    get   ':slug/dashboard/projects/:id',   to: 'admin#project_show', as: :admin_project_show

    post  ':slug/dashboard/projects/create',      to: 'projects#create',  as: :admin_create_project
    patch ':slug/dashboard/projects/:id/update',  to: 'projects#update',  as: :admin_update_project
    delete ':slug/dashboard/projects/:id/delete', to: 'projects#destroy', as: :admin_destroy_project

    get ':slug/dashboard/sandbox', to: 'admin#sandbox', as: :admin_sandbox
  # end

  constraints(host: /^(?!www\.)/i) do
    get '(*any)' => redirect { |params, request|
      URI.parse(request.url).tap { |uri| uri.host = "www.#{uri.host}" }.to_s
    }
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>

  <div id="notice" class="flex-cent">

    <p class="text-white border-orange background-black p-15 radius-50"><%= notice %></p>

  </div>

<% elsif alert %>

  <div id="alert" class="flex-cent">

    <p class="text-white border-red background-black p-15 radius-50"><%= alert %></p>

  </div>

<% end %>

app/views/shared/_footer.html.erb
<footer id="legallab-footer" class="flex-bet-cent">

  <div class="flex-start-rp-col flex-1 p-rp-small">
    <%= link_to t('footer.legal_notices'), legal_notices_path(lang:params[:lang] || I18n.default_locale), class: "text-black mr-20" %>
    <%= link_to t('footer.privacy_notice'), privacy_notice_path(lang:params[:lang] || I18n.default_locale), class: "text-black" %>
  </div>

  <div class="flex-end flex-1"><%= svg('ubi_x_comics_logo') %></div>

</footer>

app/views/shared/_navbar.html.erb
<nav id="legallab-navbar" class="flex-bet-cent relative text-white">

  <%= link_to root_path(lang:params[:lang]) do %>
    <h1 class="m-0" id="legallab-logo">
      <%= svg('logo_i') %>
      <span class="mr-15"></span>
      <%= svg(t('navbar.logo')) %>
    </h1>
  <% end %>

  <%= render "shared/navbar_components/menu" %>

  <div id="dropdown_ajaxified" class="scrollable"> <!-- AJAX DROPDOWN CALL --> </div>

  <div class="flex-cent p-rp-small">
    <%= link_to "FR", { lang:"fr" }, class: "text-white #{params["lang"] == 'fr' ? 'strong' : ''}" %>
    <span class="mr-05 ml-05"> - </span>
    <%= link_to "EN", { lang:"en" }, class: "text-white #{params["lang"] == 'en' || params["lang"].nil? ? 'strong' : ''}" %>

    <%= render "shared/navbar_components/responsive/menu" %>
  </div>

</nav>